config/routes.rb
Rails.application.routes.draw do
  resources :animes
  root to: "animes#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]

  # GET /animes
  # GET /animes.json
  def index
    @animes = Anime.all
    # lista todos as notas de forma decrescente
    @animes = Anime.order('grade DESC').all
    @num = 0

  end

  # GET /animes/1
  # GET /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes
  # POST /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime was successfully created.' }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1
  # PATCH/PUT /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:title, :grade, :resume, :num)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div class="message is-warning">
      <div class="message-header">
        <h2><%= pluralize(anime.errors.count, "error") %> prohibited this book from being saved:</h2>
      </div>
      <div class="message is-body">
        <ul>
          <% anime.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :title, class: "label"%>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :grade, class: "label" %>
    <%= form.text_field :author, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :resume, class: "label" %>
    <%= form.text_area :resume, class: "textarea", placeholder:"Escreva um breve resumo...", rows:"10"%>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success"%>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<p id="notice"><%= notice %></p>

<div id="table_attr">
  <table id="tab" class="table is-bordered">
    <thead>
        <th></th>
        <th>Título</th>
        <th>Nota</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
      <% @animes.each do |anime| %>
          <td id="number"><span class="nth"><%= @num += 1 %></span></td>
          <td><%= anime.title %></td>
          <td><%= anime.grade %></td>
          <td><%= link_to 'Mostrar', anime %></td>
        </tr>
      <% end %>  
    </tbody>
  </table>
</div>

<br>

app/views/animes/new.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">Novo Review</h1>
        <%= render 'form', anime: @anime %>
    </div>
</div>


<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<%= content_for :title do %>
  <%= @anime.title %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">

    <div class="panel-control">
      <strong>Nota:</strong>
      <%= @anime.grade %>
    </div>

    <div class="panel-control"> 
      <strong>Resumo:</strong>
      <%= @anime.resume %>
    </div><br>
    <div id="back_button" class="button is-white">
      << <%= link_to 'Voltar', animes_path %>
    </div>
    <%= link_to 'Editar', edit_anime_path(@anime), class: "button is-link is-light" %>
    <%= link_to 'Excluir', anime_path(@anime), 
        method: :delete, date: {confirm: "Are you sure?"}, 
        class: "button is-danger is-light" %>
  </div>
  
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myanimelist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>